#ifndef ESP32_DRONE_CONSTANTS_H
#define ESP32_DRONE_CONSTANTS_H

#define LOGGER_BAUDRATE (115200)

#define GPIO_I2C_SDA (8)
#define GPIO_I2C_SCL (9)

#define SENSOR_INIT_MAX_TRY (5)
#define SENSOR_POLL_MAX_INVALID (5)

#define MPU6050_CMD_RESET (0x80)

#endif /*  ESP32_DRONE_CONSTANTS_H */